"""Initial Migration

Revision ID: 483b0aefbf22
Revises: 9fea2990c496
Create Date: 2021-09-20 00:15:48.232412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483b0aefbf22'
down_revision = '9fea2990c496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('dislikes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'dislikes')
    op.drop_column('pitches', 'likes')
    # ### end Alembic commands ###
